#%RAML 1.0 NamedExample

  {
            "accountNum": "1234567857",
            "atmPin": "2233",
            "ifscCode": "HDFC00022",
            "depositAmount": 0,
            "mailId": "vitschool92@gmail.com",
            "contact": 876454332
            }